image: golang:1.15.5

variables:
  PROJECT_NAME: "terraform-provider-atn"

cache:
  paths:
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in
stages:
  - test
  - build
before_script:
  - chmod +x ./tools/coverage.sh
  - mkdir -p /go/src/github.com/allence-tunisie /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/allence-tunisie/terraform-provider-atn
  - ln -s /go/src/github.com/allence-tunisie /go/src/_/builds/allence-tunisie
  - go get -v -d ./...

unit_tests:
  stage: test
  tags:
    - aws-runner
  script:
    - go test -v ./...
code_coverage_report:
  stage: test
  tags:
    - aws-runner
  script:
    - ./tools/coverage.sh html
  only:
    - master
build:
  stage: build
  tags:
    - aws-runner
  script:
    - go build -i -v